path: H:/Study/YoloForSurface/yolo_neudet

train: ../datasets/neudet_yolo_cleaned_train.txt
val: ../datasets/neudet_yolo_cleaned_val.txt

nc: 6
names:
  0: crazing
  1: inclusion
  2: patches
  3: pitted_surface
  4: rolled-in_scale
  5: scratches
